/*
-- Query: SELECT * FROM avella.drug_category
-- Date: 2017-06-28 22:23
*/
INSERT INTO `drug_category` (`ID`,`CATEGORY_NAME`) VALUES (1,'LONG ACTING');
INSERT INTO `drug_category` (`ID`,`CATEGORY_NAME`) VALUES (2,'STIMULANTS');
INSERT INTO `drug_category` (`ID`,`CATEGORY_NAME`) VALUES (3,'ANTI-DEPRESSANTS');
INSERT INTO `drug_category` (`ID`,`CATEGORY_NAME`) VALUES (4,'TRANSMUCOSAL IMMEDIATE RELEASE FENTANYL (TIRF)');
INSERT INTO `drug_category` (`ID`,`CATEGORY_NAME`) VALUES (5,'OPIOID/ALCOHOL DEPENDENCE');
INSERT INTO `drug_category` (`ID`,`CATEGORY_NAME`) VALUES (6,'MISCELLANEOUS');
INSERT INTO `drug_category` (`ID`,`CATEGORY_NAME`) VALUES (7,'FAST ACTING/BREAKTHROUGH');
